name: Send a weekly digest
on:
  workflow_dispatch:
  schedule:
    # Looking to schedule every Sunday at 15:00 GMT-5 (or 20:00 GMT)
    # [minute] [hour] [day] [month] [day of week (SUN = 0)]
    - cron: '0 20 * * 0'
jobs:
  schedule-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          yarn install --production
      - name: Execute script
        run:
          node ./scripts/auto-publish.mjs
        env:
          GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
          GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
