name: Add default tag to untagged posts
on:
  workflow_dispatch:
jobs:
  retag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          yarn install --production
      - name: Execute script
        run: |
          node ./scripts/retag.js
        env:
          ADMIN_URL: ${{ secrets.GHOST_ADMIN_API_URL  }}
          ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
          CONTENT_API_KEY: ${{ secrets.GHOST_CONTENT_API_KEY }}
          FALLBACK_TAG_ID: "6669fed4e4492f15135d7a7d"
