name: Test and Deploy Theme
on:
  push:
    branches:
      - staging
jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Test Theme
        run: |
          yarn install
          yarn gulp zip
          yarn test:ci
      - name: Deploy Theme
        run: |
          GHOST_JWT=$(node ./scripts/admin-jwt.js)
          curl -X POST \
          -H "Authorization: Bearer $GHOST_JWT" \
          -H "CF-Access-Client-Id: $CF_CID" \
          -H "CF-Access-Client-Secret: $CF_SEC"\
          $GHOST_ADMIN_API_URL/api/admin/themes/upload/\
          -F file=@./dist/rene.zip
        env:
          GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
          GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
          CF_CID: ${{ secrets.RG_STAGING_CLIENT_ID }}
          CF_SEC: ${{ secrets.RG_STAGING_CLIENT_SECRET }}
