name: Test and Deploy Theme
on:
  push:
    branches:
      - staging
jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Test Theme
        run: |
          yarn install
          yarn test:ci
      - name: Authenticate
        uses: Boostport/setup-cloudflare-warp@v1
        with:
          organization: your-organization
          auth_client_id: ${{ secrets.RG_STAGING_CLIENT_ID }}
          auth_client_secret: ${{ secrets.RG_STAGING_CLIENT_SECRET }}
      - name: Deploy Theme
        uses: TryGhost/action-deploy-theme@v1.6.6
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
