name: Test and Deploy Theme
on:
  push:
    branches:
      - master
jobs:
  automate:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test Theme
        run: |
          yarn install
          yarn test:ci
      - name: Deploy Theme
        uses: TryGhost/action-deploy-theme@v1.4.1
        with:
          api-url: https://renegalindo.com
          api-key: 60eaffd5cc4906da5dbaf8e8:2608bd5acfc48a93203bd612e9b04957098fc246b03a8ee37ce83f31666627a0
